proxies:
- cipher: aes-256-gcm
  name: é«˜æ€§ä»·æ¯”æœºåœº:https://kfyun.uk
  password: aes-128-gcm:6601fb90e9b3
  port: 443
  server: 127.0.0.1
  tls: false
  type: ss
- cipher: aes-256-gcm
  name: 0|--1
  password: aes-256-cfb:qwerREWQ@@
  port: 51199
  server: 221.139.79.20
  tls: false
  type: ss
- cipher: aes-256-gcm
  name: 0|--3
  password: aes-256-cfb:amazonskr05
  port: 443
  server: 13.231.234.231
  tls: false
  type: ss
- cipher: aes-256-gcm
  name: 0|--5
  password: rc4-md5:14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 68.183.227.45
  tls: false
  type: ss
- cipher: aes-256-gcm
  name: 0|--9
  password: chacha20-ietf-poly1305:J0lgxy4mb52CIJ8UUcEgts
  port: 3089
  server: 51.13.182.231
  tls: false
  type: ss
- cipher: aes-256-gcm
  name: 0|--10
  password: aes-256-cfb:qwerREWQ@@
  port: 37041
  server: 121.170.203.147
  tls: false
  type: ss
- name: 103.44.255.81
  password: ouo
  port: 443
  server: 103.44.255.81
  tls: true
  type: trojan
- alterId: 64
  cipher: auto
  name: 13|ğŸ‡­ğŸ‡° é¦™æ¸¯2|@ripaojiedian
  port: 48109
  server: 183.236.51.23
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 64
  cipher: auto
  name: 13|ğŸ‡­ğŸ‡° é¦™æ¸¯3|@ripaojiedian
  port: 54104
  server: 183.236.51.23
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 64
  cipher: auto
  name: 13|ğŸ‡­ğŸ‡° é¦™æ¸¯6|@ripaojiedian
  port: 44614
  server: 120.198.71.219
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- cipher: aes-256-gcm
  name: 13|ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  password: chacha20-ietf-poly1305:9e2a92c6-bbe6-49fa-a280-e6f8f3eed7c5
  port: 30228
  server: pretw.capoonetwork.com
  tls: false
  type: ss
- alterId: 0
  cipher: auto
  name: 13|ğŸ‡¯ğŸ‡µ æ—¥æœ¬|@ripaojiedian
  port: 19690
  server: ywtwepcnwlou.xn--fiqs8sjz2bull.com
  tls: false
  type: vmess
  uuid: 38eda6f2-6e04-4484-8f82-e859e76612d6
- name: 154.83.91.150
  password: ouo
  port: 443
  server: 154.83.91.150
  tls: true
  type: trojan
- cipher: aes-256-gcm
  name: 13|ğŸ‡¯ğŸ‡µ æ—¥æœ¬3|@ripaojiedian
  password: chacha20-ietf-poly1305:9e2a92c6-bbe6-49fa-a280-e6f8f3eed7c5
  port: 19550
  server: prejp.capoonetwork.com
  tls: false
  type: ss
- name: 132.226.171.151
  password: ouo
  port: 40274
  server: 132.226.171.151
  tls: true
  type: trojan
- cipher: aes-256-gcm
  name: 13|ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡|@ripaojiedian
  password: chacha20-ietf-poly1305:f16d3752-7bae-474e-87dc-f892df2caeaf
  port: 31620
  server: ctmm.gscloud.bond
  tls: false
  type: ss
- alterId: 0
  cipher: auto
  name: 13|ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡2|@ripaojiedian
  port: 53896
  server: pudvkjvvgdol.xn--fiqs8sjz2bull.com
  tls: false
  type: vmess
  uuid: 38eda6f2-6e04-4484-8f82-e859e76612d6
- alterId: 0
  cipher: auto
  name: 13|ğŸ‡ºğŸ‡¸ ç¾å›½|@ripaojiedian
  port: 46833
  server: 38.147.161.252
  tls: false
  type: vmess
  uuid: 77175906-b651-4c44-9397-04b30a602c0c
- cipher: aes-256-gcm
  name: 13|ğŸ‡°ğŸ‡· éŸ©å›½ç‰¹æ®Š|@ripaojiedian
  password: aes-256-cfb:amazonskr05
  port: 443
  server: 3.35.54.92
  tls: false
  type: ss
- cipher: aes-256-gcm
  name: 13|ğŸ‡¸ğŸ‡¬ ç‹®åŸç‰¹æ®Š|@ripaojiedian
  password: aes-256-cfb:amazonskr05
  port: 443
  server: 43.207.72.50
  tls: false
  type: ss
- cipher: aes-256-gcm
  name: 13|ğŸ‡¯ğŸ‡µ æ—¥æœ¬ç‰¹æ®Š|@ripaojiedian
  password: aes-256-cfb:amazonskr05
  port: 443
  server: 54.180.250.244
  tls: false
  type: ss
- alterId: 0
  cipher: auto
  name: 13|ğŸ‡©ğŸ‡ª å¾·å›½|@ripaojiedian
  port: 2082
  server: 64.225.109.206
  tls: false
  type: vmess
  uuid: 48264b45-64b8-4e9f-8a88-cef41f20c736
- name: 103.44.255.81
  password: ouo
  port: 443
  server: 103.44.255.81
  tls: true
  type: trojan
- alterId: 64
  cipher: auto
  name: 14|é¦™æ¸¯2|@ripaojiedian
  port: '48109'
  server: 183.236.51.23
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 64
  cipher: auto
  name: 14|é¦™æ¸¯3|@ripaojiedian
  port: '54104'
  server: 183.236.51.23
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 64
  cipher: auto
  name: 14|é¦™æ¸¯6|@ripaojiedian
  port: '44614'
  server: 120.198.71.219
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- cipher: aes-256-gcm
  name: 14|å°æ¹¾|@ripaojiedian
  password: ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo5ZTJhOTJjNi1iYmU2LTQ5ZmEtYTI4MC1lNmY4ZjNlZWQ3YzU
  port: 30228
  server: pretw.capoonetwork.com
  tls: false
  type: ss
- alterId: 0
  cipher: auto
  name: 14|æ—¥æœ¬|@ripaojiedian
  port: '19690'
  server: ywtwepcnwlou.xn--fiqs8sjz2bull.com
  tls: false
  type: vmess
  uuid: 38eda6f2-6e04-4484-8f82-e859e76612d6
- name: 154.83.91.150
  password: ouo
  port: 443
  server: 154.83.91.150
  tls: true
  type: trojan
- cipher: aes-256-gcm
  name: 14|æ—¥æœ¬3|@ripaojiedian
  password: ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo5ZTJhOTJjNi1iYmU2LTQ5ZmEtYTI4MC1lNmY4ZjNlZWQ3YzU
  port: 19550
  server: prejp.capoonetwork.com
  tls: false
  type: ss
- name: 132.226.171.151
  password: ouo
  port: 40274
  server: 132.226.171.151
  tls: true
  type: trojan
- cipher: aes-256-gcm
  name: 14|æ–°åŠ å¡|@ripaojiedian
  password: ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpmMTZkMzc1Mi03YmFlLTQ3NGUtODdkYy1mODkyZGYyY2FlYWY
  port: 31620
  server: ctmm.gscloud.bond
  tls: false
  type: ss
- alterId: 0
  cipher: auto
  name: 14|æ–°åŠ å¡2|@ripaojiedian
  port: '53896'
  server: pudvkjvvgdol.xn--fiqs8sjz2bull.com
  tls: false
  type: vmess
  uuid: 38eda6f2-6e04-4484-8f82-e859e76612d6
- alterId: 0
  cipher: auto
  name: 14|ç¾å›½|@ripaojiedian
  port: '46833'
  server: 38.147.161.252
  tls: false
  type: vmess
  uuid: 77175906-b651-4c44-9397-04b30a602c0c
- cipher: aes-256-gcm
  name: 14|éŸ©å›½ç‰¹æ®Š|@ripaojiedian
  password: ss://YWVzLTI1Ni1jZmI6YW1hem9uc2tyMDU
  port: 443
  server: 3.35.54.92
  tls: false
  type: ss
- cipher: aes-256-gcm
  name: 14|ç‹®åŸç‰¹æ®Š|@ripaojiedian
  password: ss://YWVzLTI1Ni1jZmI6YW1hem9uc2tyMDU
  port: 443
  server: 43.207.72.50
  tls: false
  type: ss
- cipher: aes-256-gcm
  name: 14|æ—¥æœ¬ç‰¹æ®Š|@ripaojiedian
  password: ss://YWVzLTI1Ni1jZmI6YW1hem9uc2tyMDU
  port: 443
  server: 54.180.250.244
  tls: false
  type: ss
- alterId: 0
  cipher: auto
  name: 14|å¾·å›½|@ripaojiedian
  port: '2082'
  server: 64.225.109.206
  tls: false
  type: vmess
  uuid: 48264b45-64b8-4e9f-8a88-cef41f20c736
- alterId: 0
  cipher: auto
  name: 16|d*********g.com_2
  port: '443'
  server: 42.236.73.72
  tls: false
  type: vmess
  uuid: 044f0177-0675-4dcf-89d4-804b6788e518
- name: 42.236.73.72
  password: fuck
  port: 443
  server: 42.236.73.72
  tls: true
  type: trojan
proxy-groups:
- name: Proxy
  proxies:
  - é«˜æ€§ä»·æ¯”æœºåœº:https://kfyun.uk
  - 0|--1
  - 0|--3
  - 0|--5
  - 0|--9
  - 0|--10
  - 103.44.255.81
  - 13|ğŸ‡­ğŸ‡° é¦™æ¸¯2|@ripaojiedian
  - 13|ğŸ‡­ğŸ‡° é¦™æ¸¯3|@ripaojiedian
  - 13|ğŸ‡­ğŸ‡° é¦™æ¸¯6|@ripaojiedian
  - 13|ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  - 13|ğŸ‡¯ğŸ‡µ æ—¥æœ¬|@ripaojiedian
  - 154.83.91.150
  - 13|ğŸ‡¯ğŸ‡µ æ—¥æœ¬3|@ripaojiedian
  - 132.226.171.151
  - 13|ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡|@ripaojiedian
  - 13|ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡2|@ripaojiedian
  - 13|ğŸ‡ºğŸ‡¸ ç¾å›½|@ripaojiedian
  - 13|ğŸ‡°ğŸ‡· éŸ©å›½ç‰¹æ®Š|@ripaojiedian
  - 13|ğŸ‡¸ğŸ‡¬ ç‹®åŸç‰¹æ®Š|@ripaojiedian
  - 13|ğŸ‡¯ğŸ‡µ æ—¥æœ¬ç‰¹æ®Š|@ripaojiedian
  - 13|ğŸ‡©ğŸ‡ª å¾·å›½|@ripaojiedian
  - 103.44.255.81
  - 14|é¦™æ¸¯2|@ripaojiedian
  - 14|é¦™æ¸¯3|@ripaojiedian
  - 14|é¦™æ¸¯6|@ripaojiedian
  - 14|å°æ¹¾|@ripaojiedian
  - 14|æ—¥æœ¬|@ripaojiedian
  - 154.83.91.150
  - 14|æ—¥æœ¬3|@ripaojiedian
  - 132.226.171.151
  - 14|æ–°åŠ å¡|@ripaojiedian
  - 14|æ–°åŠ å¡2|@ripaojiedian
  - 14|ç¾å›½|@ripaojiedian
  - 14|éŸ©å›½ç‰¹æ®Š|@ripaojiedian
  - 14|ç‹®åŸç‰¹æ®Š|@ripaojiedian
  - 14|æ—¥æœ¬ç‰¹æ®Š|@ripaojiedian
  - 14|å¾·å›½|@ripaojiedian
  - 16|d*********g.com_2
  - 42.236.73.72
  type: select
rules:
- domain: google.com
  outboundTag: Proxy
  type: field
- domain: youtube.com
  outboundTag: Proxy
  type: field
- ip: 8.8.8.8
  outboundTag: Proxy
  type: field
- ip: 0.0.0.0/0
  outboundTag: DIRECT
  type: field
- outboundTag: DIRECT
  type: final
