name: Actions-merge-clash-yaml

on:
  workflow_dispatch:    # 手动触发
  schedule:
    - cron: '0 */8 * * *'  # 8小时一次

jobs:
  update_yaml_configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: 查看CPU 内存 硬盘
        if: (!cancelled())
        run: cat /proc/cpuinfo && cat /proc/meminfo && df -hT
        
      - name: 创建配置文件目录
        run: |
          echo "创建配置文件目录"
          mkdir -p ./configs
          echo "Configs directory created"
        
      - name: 下载 yaml 文件
        run: |
          YAML_URL1="https://little-thunder-d99c.linzf5039.workers.dev/335581?clash"
          YAML_URL2="https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml"
          YAML_URL3="https://clashgithub.com/wp-content/uploads/rss/20250126.yml" # 动态生成 YAML_URL3
          #YAML_URL3="https://clashgithub.com/wp-content/uploads/rss/$(date +%Y%m%d).yml" # 动态生成 YAML_URL3
          curl -f -o ./configs/config1.yaml $YAML_URL1 || exit 1
          curl -f -o ./configs/config2.yaml $YAML_URL2 || exit 1
          curl -f -o ./configs/config3.yaml $YAML_URL3 || exit 1

      - name: 安装 Python 3 和依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests pyyaml ruamel.yaml # 安装 ruamel.yaml

      - name: 合并YAML
        run: |
          python3 merge_yaml.py

      - name: 拉取最新代码
        run: git pull

      - name: 检查是否有更改
        run: |
          git status
          if [[ -z "$(git status -s)" ]]; then
            echo "没有更改，无需提交"
            exit 0
          fi

      - name: 添加文件目录到 Git
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git add -f ./configs
          git commit -m "Add Files to configs"
          git push
